In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
df1 = pd.read_csv('cleaned_df-2', index_col = 0)

In [2]:
df = pd.read_csv('merged.csv', index_col = 0)

In [3]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_renovated,lat,long,sqft_living15,reno,sqft_living_times_grade,condition_div_grade,bathrooms_sq,median_by_zip,Closest_WF
0,221900.0,3,1.00,1180,5650,1.0,0.0,0.0,3,7,...,0.0,47.5112,-122.257,1340,0,8260,0.428571,1.0000,60839.0,12.09
1,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,3,7,...,1991.0,47.7210,-122.319,1690,1,17990,0.428571,5.0625,54561.0,10.29
2,180000.0,2,1.00,770,10000,1.0,0.0,0.0,3,6,...,0.0,47.7379,-122.233,2720,0,4620,0.500000,1.0000,90588.0,9.59
3,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,5,7,...,0.0,47.5208,-122.393,1360,0,13720,0.714286,9.0000,90625.0,12.99
4,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,3,8,...,0.0,47.6168,-122.045,1800,0,13440,0.375000,4.0000,145262.0,6.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,360000.0,3,2.50,1530,1131,3.0,0.0,0.0,3,8,...,0.0,47.6993,-122.346,1530,0,12240,0.375000,6.2500,81330.0,7.29
21593,400000.0,4,2.50,2310,5813,2.0,0.0,0.0,3,8,...,0.0,47.5107,-122.362,1830,0,18480,0.375000,6.2500,58429.0,14.11
21594,402101.0,2,0.75,1020,1350,2.0,0.0,0.0,3,7,...,0.0,47.5944,-122.299,1020,0,7140,0.428571,0.5625,62633.0,7.43
21595,400000.0,3,2.50,1600,2388,2.0,0.0,0.0,3,8,...,0.0,47.5345,-122.069,1410,0,12800,0.375000,6.2500,102025.0,12.76
21596,325000.0,2,0.75,1020,1076,2.0,0.0,0.0,3,7,...,0.0,47.5941,-122.299,1020,0,7140,0.428571,0.5625,62633.0,7.44

In [ ]:
function to plot quantiles, takes in a model and 10 bins

In [ ]:
pd.qcut(y), bins

In [ ]:
frame = pd.DataFrame(groups)

In [ ]:
frame['error' = est.predict(x)-y]

In [ ]:
frame.columns = ['bins', 'error',]

In [ ]:
frame = frame.groupby['bins'].mean()

In [ ]:
frame.plot(kind = bar)

Break this data into quantiles